### ISSUE TITLE
Ошибка при установке

### ISSUE THREAD

**Issue by dva-re** [AlexMKX/mrvpn#1]
```
TASK [mrvpn : Installing Firezone] *********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: /srv/mrvpn/firezone_install.sh.
fatal: [gate.host]: FAILED! => {"changed": false, "msg": "The command was not found or was not executable: /srv/mrvpn/firezone_install.sh."}
```

Возможно из-за  /tmp в https://github.com/AlexMKX/mrvpn/blob/master/roles/mrvpn/tasks/firezone.yml#L12

**Comment by dva-re** [comment]
сюда же, если поправить путь до инсталлера firezone и пройти дальше 

```
TASK [mrvpn : Configuring] ******************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'MTU' is undefined
fatal: [gate.host]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'MTU' is undefined"}
```

Возможно я что-то делаю не так, но попробовал и на debian и на ubuntu, результат одинаковый
Подскажите, на какие конкретно версиях ОС вы обкатывали скрипт, я попробую на них.

**Comment by ignasio** [comment]
Если бы был vagrant box на все провайдеры, то цены бы не было! Крутяк!

**Comment by AlexMKX** [comment]
В новом релизе данные проблемы будут починены.

**Comment by AlexMKX** [comment]
@dva-re обкатывалось на свежей убунте.

**Comment by AlexMKX** [comment]
Починено в свежем релизе. MTU больше не нужен т.к. используется MTU-Clamping
Так же в свежем релизе корректно работает запуск инсталлера firezone
