### ISSUE TITLE
Недостаточность документации

### ISSUE THREAD

**Issue by dE1l** [AlexMKX/mrvpn#2]
Ansible хоть и популярный инструмент, но в узких кругах.

Реализация крутая. Но вот порог входа даже для хорошо подкованного технически человека очень высок.

Что бы помогло облегчить жизнь:
- Хочется Docker. В него все умеют нынче.
- Инструкция как интегрировать данную разработку в Raspberry (снова привет Docker)
- Непонятно откуда взять WireGuard Server для OuterNet и как за него заплатить в нынешних реалиях
- Не очевидно получится ли использовать данное решение в обычном домашнем wifi роутере аля Asus или TpLink чтобы завернуть весь домашний трафик сразу для всех устройств

**Comment by AlexMKX** [comment]
Докер (полностью) к сожалению невозможно :( Firezone тянет свои контейнеры. 
Вторая причина - у меня нормально, к сожалению, wg внутри докера не завелся. Там роутинг поднимается только с бубном.
